language: python 
    python:
      - "3.4"
     
    services: 
      - postgresql
    env: 
      -DJANGO=2.0.5 DB=postgresql
    install:
      - pip install -r requirements.txt
    before_script: 
      - postgresql -e 'create database test;' -u root
    script: 
      - python manage.py test